// lib/subsidyData.js
// Government Schemes & Subsidies Database

export const GOVERNMENT_SCHEMES = [
  {
    id: 'pm-awas',
    name: 'PM Awas Yojana (Urban)',
    ministry: 'Ministry of Housing',
    category: 'Housing',
    benefit: 'Interest subsidy up to ₹2.67L on home loans',
    eligibility: ['Annual household income up to ₹18L', 'First-time homebuyer', 'No pucca house in any part of India'],
    forWhom: ['Salaried', 'Self-Employed', 'Business'],
    link: 'https://pmaymis.gov.in/',
    active: true,
  },
  {
    id: 'mudra',
    name: 'MUDRA Loan Scheme',
    ministry: 'Ministry of Finance',
    category: 'Business',
    benefit: 'Collateral-free loans up to ₹10L for micro enterprises',
    eligibility: ['Non-corporate, non-farm small/micro enterprise', 'Shishu: up to ₹50K, Kishore: ₹50K-5L, Tarun: ₹5L-10L'],
    forWhom: ['Self-Employed', 'Business'],
    link: 'https://www.mudra.org.in/',
    active: true,
  },
  {
    id: 'startup-india',
    name: 'Startup India',
    ministry: 'DPIIT',
    category: 'Business',
    benefit: 'Tax exemption for 3 years, self-certification, fast-track patents',
    eligibility: ['Incorporated as Pvt Ltd, LLP, or Partnership', 'Turnover < ₹100Cr in any FY', 'Entity age < 10 years', 'Working towards innovation/improvement'],
    forWhom: ['Business'],
    link: 'https://www.startupindia.gov.in/',
    active: true,
  },
  {
    id: 'standup-india',
    name: 'Stand-Up India',
    ministry: 'Ministry of Finance',
    category: 'Business',
    benefit: 'Bank loans ₹10L to ₹1Cr for SC/ST/Women entrepreneurs',
    eligibility: ['SC/ST or Women entrepreneur', 'Above 18 years', 'Greenfield enterprise', 'Not a defaulter'],
    forWhom: ['Self-Employed', 'Business'],
    link: 'https://www.standupmitra.in/',
    active: true,
  },
  {
    id: 'msme-tech',
    name: 'MSME Technology Upgrade Scheme',
    ministry: 'Ministry of MSME',
    category: 'Business',
    benefit: 'Capital subsidy of 15% on eligible plant & machinery',
    eligibility: ['Registered MSME', 'Manufacturing sector', 'Investment in technology upgrade'],
    forWhom: ['Business'],
    link: 'https://msme.gov.in/',
    active: true,
  },
  {
    id: 'atal-pension',
    name: 'Atal Pension Yojana',
    ministry: 'Ministry of Finance',
    category: 'Pension',
    benefit: 'Guaranteed pension of ₹1,000-₹5,000/month after 60',
    eligibility: ['Age 18-40', 'Bank account holder', 'Not an income tax payer (for govt co-contribution)'],
    forWhom: ['Salaried', 'Self-Employed'],
    link: 'https://npscra.nsdl.co.in/scheme-details.php',
    active: true,
  },
  {
    id: 'pm-jeevan-jyoti',
    name: 'PM Jeevan Jyoti Bima Yojana',
    ministry: 'Ministry of Finance',
    category: 'Insurance',
    benefit: 'Life insurance cover of ₹2L at ₹436/year',
    eligibility: ['Age 18-50', 'Bank account holder', 'Aadhar linked'],
    forWhom: ['Salaried', 'Self-Employed', 'Business'],
    link: 'https://jansuraksha.gov.in/',
    active: true,
  },
  {
    id: 'pm-suraksha',
    name: 'PM Suraksha Bima Yojana',
    ministry: 'Ministry of Finance',
    category: 'Insurance',
    benefit: 'Accident insurance cover of ₹2L at ₹20/year',
    eligibility: ['Age 18-70', 'Bank account holder'],
    forWhom: ['Salaried', 'Self-Employed', 'Business'],
    link: 'https://jansuraksha.gov.in/',
    active: true,
  },
  {
    id: 'sukanya',
    name: 'Sukanya Samriddhi Yojana',
    ministry: 'Ministry of Finance',
    category: 'Savings',
    benefit: 'High interest (8.2%) + 80C benefit for girl child savings',
    eligibility: ['Girl child below 10 years', 'Max 2 accounts', 'Indian resident'],
    forWhom: ['Salaried', 'Self-Employed', 'Business'],
    link: 'https://www.nsiindia.gov.in/',
    active: true,
  },
  {
    id: 'pm-kisan',
    name: 'PM-KISAN',
    ministry: 'Ministry of Agriculture',
    category: 'Agriculture',
    benefit: '₹6,000/year direct benefit transfer in 3 installments',
    eligibility: ['Small and marginal farmer families', 'Cultivable land holding'],
    forWhom: ['Self-Employed'],
    link: 'https://pmkisan.gov.in/',
    active: true,
  },
  {
    id: 'ayushman-bharat',
    name: 'Ayushman Bharat (PMJAY)',
    ministry: 'Ministry of Health',
    category: 'Healthcare',
    benefit: 'Health cover up to ₹5L/family/year for secondary & tertiary care',
    eligibility: ['Deprived families as per SECC data', 'No limit on family size', 'Cashless treatment'],
    forWhom: ['Salaried', 'Self-Employed'],
    link: 'https://pmjay.gov.in/',
    active: true,
  },
  {
    id: 'agnii',
    name: 'AGNIi (Innovation)',
    ministry: 'Office of PSA',
    category: 'Innovation',
    benefit: 'Bridge between innovators and industry/government for deployment',
    eligibility: ['Indian innovators/startups', 'Technology-based solutions', 'Scalable innovations'],
    forWhom: ['Business'],
    link: 'https://agnii.gov.in/',
    active: true,
  },
];

export function findEligibleSchemes(userType) {
  return GOVERNMENT_SCHEMES.filter(
    (s) => s.active && s.forWhom.includes(userType)
  );
}
